import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');

export const PATHS = {
  repoRoot: REPO_ROOT,
  pgeTerritory: path.join(REPO_ROOT, 'src/data/pgeTerritory.json'),
  sceTerritory: path.join(REPO_ROOT, 'src/data/sceTerritory.json'),
  multiUtilityZips: path.join(REPO_ROOT, 'src/data/multiUtilityZips.json'),
  serviceAreas: path.join(REPO_ROOT, 'src/data/serviceAreas.json'),
  pgeRatePlans: path.join(REPO_ROOT, 'src/data/ratePlans.json'),
  sceRatePlans: path.join(REPO_ROOT, 'src/data/sceRatePlans.json'),
  ratePlanRegistry: path.join(REPO_ROOT, 'src/data/ratePlanRegistry.js'),
  territorySources: path.join(REPO_ROOT, 'data-sources/territory'),
  verifiedZips: path.join(REPO_ROOT, 'data-sources/territory/verified-zips.json'),
  manualOverrides: path.join(REPO_ROOT, 'data-sources/territory/manual-overrides.json'),
  sourceManifest: path.join(REPO_ROOT, 'data-sources/territory/source-manifest.json'),
  buildReport: path.join(REPO_ROOT, 'data-sources/territory/build-report.json'),
  zctaRaw: path.join(REPO_ROOT, 'data-sources/territory/raw/zcta-ca-2024.geojson'),
  overlayCandidates: path.join(REPO_ROOT, 'data-sources/territory/overlay-candidates.json'),
  ccaServiceAreaMap: path.join(REPO_ROOT, 'data-sources/territory/cca-service-area-map.json'),
};

const UTILITY_CONFIG = {
  'PG&E': { bundledProvider: 'pge', rateFileKey: 'pge' },
  SCE: { bundledProvider: 'sce', rateFileKey: 'sce' },
};

export function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

export function fileSha256(filePath) {
  const buffer = fs.readFileSync(filePath);
  return crypto.createHash('sha256').update(buffer).digest('hex');
}

export function sortObjectByKey(value) {
  if (Array.isArray(value)) {
    return value.map(sortObjectByKey);
  }
  if (!value || typeof value !== 'object') {
    return value;
  }
  return Object.fromEntries(
    Object.keys(value)
      .sort()
      .map(key => [key, sortObjectByKey(value[key])])
  );
}

export function formatJson(value) {
  return `${JSON.stringify(sortObjectByKey(value), null, 2)}\n`;
}

export function buildTerritoryData({ verifiedZips, manualOverrides = [] }) {
  const pge = { ...(verifiedZips?.pge?.zips ?? {}) };
  const sce = { ...(verifiedZips?.sce?.zips ?? {}) };
  const multi = { ...(verifiedZips?.multiUtility?.zips ?? {}) };
  const excluded = { ...(verifiedZips?.excluded?.zips ?? {}) };
  const appliedOverrides = [];

  for (const override of manualOverrides) {
    if (!override?.zip || !override.action) continue;

    if (override.action === 'assign') {
      delete multi[override.zip];
      delete excluded[override.zip];
      if (override.utility === 'PG&E') {
        delete sce[override.zip];
        pge[override.zip] = override.serviceAreaId;
      } else if (override.utility === 'SCE') {
        delete pge[override.zip];
        sce[override.zip] = override.serviceAreaId;
      }
    }

    if (override.action === 'multiUtility') {
      multi[override.zip] = [...override.candidates].sort();
    }

    if (override.action === 'exclude') {
      delete pge[override.zip];
      delete sce[override.zip];
      delete multi[override.zip];
      excluded[override.zip] = {
        reason: override.reason,
        source: override.source,
      };
    }

    appliedOverrides.push({
      zip: override.zip,
      action: override.action,
      reason: override.reason,
      source: override.source,
    });
  }

  return {
    pgeTerritory: {
      _note: 'zipcode → serviceAreaId for PG&E territory. Generated by scripts/build-territory.js from committed territory source snapshots and documented overrides.',
      zips: pge,
    },
    sceTerritory: {
      _note: 'SCE service territory ZIP codes → service area ID. Generated by scripts/build-territory.js from committed territory source snapshots and documented overrides.',
      zips: sce,
    },
    multiUtilityZips: {
      _note: 'ZIPs where a single code spans multiple utility territories. User must select their utility. Generated by scripts/build-territory.js.',
      zips: multi,
    },
    excluded,
    appliedOverrides,
  };
}

export function loadCurrentTerritoryData() {
  return {
    pgeTerritory: readJson(PATHS.pgeTerritory),
    sceTerritory: readJson(PATHS.sceTerritory),
    multiUtilityZips: readJson(PATHS.multiUtilityZips),
  };
}

export function loadVerifiedZips() {
  const source = readJson(PATHS.verifiedZips);
  if (source.bootstrapFromRuntime) {
    const current = loadCurrentTerritoryData();
    return {
      ...source,
      pge: { zips: current.pgeTerritory.zips },
      sce: { zips: current.sceTerritory.zips },
      multiUtility: { zips: current.multiUtilityZips.zips },
    };
  }
  return source;
}

export function loadManualOverrides() {
  return readJson(PATHS.manualOverrides).overrides ?? [];
}

export function loadRateRegistryIds(registryPath = PATHS.ratePlanRegistry) {
  const source = fs.readFileSync(registryPath, 'utf8');
  return new Set([...source.matchAll(/['"]([a-z0-9-]+)['"]\s*:/g)].map(match => match[1]));
}

function addIssue(issues, message, details = {}) {
  issues.push({ message, ...details });
}

function getRateDataForUtility(ratePlanFiles, utility) {
  const config = UTILITY_CONFIG[utility];
  return config ? ratePlanFiles[config.rateFileKey] : null;
}

function providerExistsInAnyPlan(rateData, provider) {
  return Object.values(rateData.ratePlans ?? {}).some(plan => plan.rates?.ccaGeneration?.[provider]);
}

function providerExistsInPlan(rateData, planId, provider) {
  return Boolean(rateData.ratePlans?.[planId]?.rates?.ccaGeneration?.[provider]);
}

export function validateTerritoryData({
  pgeTerritory,
  sceTerritory,
  multiUtilityZips,
  serviceAreas,
  ratePlanFiles,
  rateRegistryIds,
  manifest = null,
}) {
  const errors = [];
  const warnings = [];
  const knownServiceAreaIds = new Set(Object.keys(serviceAreas.serviceAreas ?? serviceAreas));
  const serviceAreaMap = serviceAreas.serviceAreas ?? serviceAreas;
  const pgeZips = pgeTerritory.zips ?? {};
  const sceZips = sceTerritory.zips ?? {};
  const multiZips = multiUtilityZips.zips ?? {};
  const usedServiceAreaIds = new Set();

  for (const [zip, serviceAreaId] of Object.entries(pgeZips)) {
    usedServiceAreaIds.add(serviceAreaId);
    if (!knownServiceAreaIds.has(serviceAreaId)) {
      addIssue(errors, `PG&E ZIP ${zip} references unknown serviceAreaId ${serviceAreaId}`, { zip, serviceAreaId });
    }
  }

  for (const [zip, serviceAreaId] of Object.entries(sceZips)) {
    usedServiceAreaIds.add(serviceAreaId);
    if (!knownServiceAreaIds.has(serviceAreaId)) {
      addIssue(errors, `SCE ZIP ${zip} references unknown serviceAreaId ${serviceAreaId}`, { zip, serviceAreaId });
    }
  }

  for (const [zip, candidates] of Object.entries(multiZips)) {
    if (!Array.isArray(candidates) || candidates.length < 2) {
      addIssue(errors, `Multi-utility ZIP ${zip} must list at least two candidates`, { zip });
      continue;
    }
    for (const serviceAreaId of candidates) {
      usedServiceAreaIds.add(serviceAreaId);
      if (!knownServiceAreaIds.has(serviceAreaId)) {
        addIssue(errors, `Multi-utility ZIP ${zip} references unknown serviceAreaId ${serviceAreaId}`, { zip, serviceAreaId });
      }
    }
  }

  for (const zip of Object.keys(pgeZips)) {
    if (sceZips[zip] && !multiZips[zip]) {
      addIssue(
        errors,
        `ZIP ${zip} is assigned to both PG&E and SCE but is missing from multiUtilityZips.json`,
        { zip, pgeServiceAreaId: pgeZips[zip], sceServiceAreaId: sceZips[zip] }
      );
    }
  }

  for (const [serviceAreaId, area] of Object.entries(serviceAreaMap)) {
    if (!rateRegistryIds.has(serviceAreaId)) {
      addIssue(errors, `Service area ${serviceAreaId} is missing from RATE_PLAN_REGISTRY`, { serviceAreaId });
    }

    const utilityConfig = UTILITY_CONFIG[area.utility];
    if (!utilityConfig) {
      addIssue(errors, `Service area ${serviceAreaId} uses unsupported utility ${area.utility}`, { serviceAreaId });
      continue;
    }

    const rateData = getRateDataForUtility(ratePlanFiles, area.utility);
    if (!rateData?.ratePlans?.[area.defaultPlanId]) {
      addIssue(errors, `Service area ${serviceAreaId} default plan ${area.defaultPlanId} is missing from ${area.utility} rate data`, { serviceAreaId });
      continue;
    }

    if (area.defaultProvider !== utilityConfig.bundledProvider && !providerExistsInPlan(rateData, area.defaultPlanId, area.defaultProvider)) {
      addIssue(errors, `Service area ${serviceAreaId} default provider ${area.defaultProvider} is missing from default plan ${area.defaultPlanId}`, { serviceAreaId });
    }

    for (const cca of area.ccas ?? []) {
      if (!providerExistsInAnyPlan(rateData, cca)) {
        addIssue(errors, `Service area ${serviceAreaId} CCA ${cca} is not present in ${area.utility} rate data`, { serviceAreaId, cca });
      }
    }
  }

  const countsByServiceArea = {};
  for (const serviceAreaId of [...Object.values(pgeZips), ...Object.values(sceZips)]) {
    countsByServiceArea[serviceAreaId] = (countsByServiceArea[serviceAreaId] ?? 0) + 1;
  }
  for (const [serviceAreaId, count] of Object.entries(countsByServiceArea)) {
    if (count > 0 && count < 5) {
      addIssue(warnings, `Service area ${serviceAreaId} has only ${count} ZIP entries; confirm this is intentional`, { serviceAreaId, count });
    }
  }

  if (manifest?.sourceMode?.includes('bootstrap')) {
    addIssue(
      warnings,
      'Territory ZIP outputs are bootstrapped from current runtime artifacts; overlay pinned CEC boundary snapshots with a reviewed ZIP/ZCTA source before broad coverage expansion'
    );
  }

  return {
    ok: errors.length === 0,
    errors,
    warnings,
    stats: {
      pgeZipCount: Object.keys(pgeZips).length,
      sceZipCount: Object.keys(sceZips).length,
      multiUtilityZipCount: Object.keys(multiZips).length,
      serviceAreaCount: knownServiceAreaIds.size,
      usedServiceAreaCount: usedServiceAreaIds.size,
    },
  };
}

export function loadValidationInputs() {
  return {
    ...loadCurrentTerritoryData(),
    serviceAreas: readJson(PATHS.serviceAreas),
    ratePlanFiles: {
      pge: readJson(PATHS.pgeRatePlans),
      sce: readJson(PATHS.sceRatePlans),
    },
    rateRegistryIds: loadRateRegistryIds(),
    manifest: fs.existsSync(PATHS.sourceManifest) ? readJson(PATHS.sourceManifest) : null,
  };
}

export function makeBuildReport({ generated, validation, manifest }) {
  return {
    generatedAt: new Date().toISOString(),
    sourceMode: manifest?.sourceMode ?? 'unknown',
    sources: manifest?.sources ?? [],
    stats: {
      ...validation.stats,
      excludedZipCount: Object.keys(generated.excluded ?? {}).length,
      appliedOverrideCount: generated.appliedOverrides.length,
    },
    warnings: validation.warnings,
    appliedOverrides: generated.appliedOverrides,
  };
}
