export const UTILITY_CONFIG = {
  pge: {
    id: 'pge',
    label: 'PG&E',
    bundledProviderId: 'pge',
    directServiceAreaId: 'pge-only',
    territoryPathKey: 'pgeTerritory',
    ratePlansPathKey: 'pgeRatePlans',
    generatedKey: 'pgeTerritory',
    verifiedKey: 'pge',
    statsKey: 'pgeZipCount',
    territoryNote: 'zipcode → serviceAreaId for PG&E territory. Generated by scripts/build-territory.js from committed territory source snapshots and documented overrides.',
  },
  sce: {
    id: 'sce',
    label: 'SCE',
    bundledProviderId: 'sce',
    directServiceAreaId: 'sce-only',
    territoryPathKey: 'sceTerritory',
    ratePlansPathKey: 'sceRatePlans',
    generatedKey: 'sceTerritory',
    verifiedKey: 'sce',
    statsKey: 'sceZipCount',
    territoryNote: 'SCE service territory ZIP codes → service area ID. Generated by scripts/build-territory.js from committed territory source snapshots and documented overrides.',
  },
  tdpud: {
    id: 'tdpud',
    label: 'TDPUD',
    bundledProviderId: 'tdpud',
    directServiceAreaId: 'tdpud-truckee',
    territoryPathKey: 'tdpudTerritory',
    ratePlansPathKey: 'tdpudRatePlans',
    generatedKey: 'tdpudTerritory',
    verifiedKey: 'tdpud',
    statsKey: 'tdpudZipCount',
    territoryNote: 'TDPUD service territory ZIP codes → service area ID. Generated by scripts/build-territory.js from committed territory source snapshots and documented overrides.',
  },
  liberty: {
    id: 'liberty',
    label: 'Liberty',
    bundledProviderId: 'liberty',
    directServiceAreaId: 'liberty-tahoe',
    territoryPathKey: 'libertyTerritory',
    ratePlansPathKey: 'libertyRatePlans',
    generatedKey: 'libertyTerritory',
    verifiedKey: 'liberty',
    statsKey: 'libertyZipCount',
    territoryNote: 'Liberty Utilities service territory ZIP codes → service area ID. Generated by scripts/build-territory.js from committed territory source snapshots and documented overrides.',
  },
};

export const UTILITY_IDS = Object.keys(UTILITY_CONFIG);

export function getUtilityById(utilityId) {
  return UTILITY_CONFIG[utilityId] ?? null;
}

export function getUtilityByLabel(label) {
  return Object.values(UTILITY_CONFIG).find(utility => utility.label === label) ?? null;
}

export function getUtilityForServiceArea(serviceArea) {
  if (!serviceArea) return null;
  return getUtilityById(serviceArea.utilityId) ?? getUtilityByLabel(serviceArea.utility);
}
